version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
      - rm package-lock.json
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  name: firehose-ui
  base-directory: build
